#datasources.default.db-type=postgres
#datasources.default.dialect=POSTGRES
#micronaut.application.name=sapatide
#datasources.default.schema-generate=CREATE_DROP
#datasources.default.driver-class-name=org.postgresql.Driver
#datasources.default.url=jdbc:postgresql://localhost:5432/money
#datasources.default.username=postgres
#datasources.default.password=satish
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    schema-generate: CREATE_DROP
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/money
    username: postgres
    password: satish

micronaut:
  application:
    name: sapatide




